/*
 * This file was automatically generated by EvoSuite
 * Mon May 13 12:59:36 GMT 2019
 */

package br.com;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.Ball;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Ball_ESTest extends Ball_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Ball ball0 = new Ball(1L, 0, 0, (String) null, (String) null, (String) null, ", firstPollOffsetStrategy=", (String) null, (String) null, "?'r &Geihd'xso_hq", "?'r &Geihd'xso_hq", "");
      String string0 = ball0.finalString();
      assertEquals("KafkaSpoutConfig{kafkaProps=null, keyDeserializer=null, valueDeserializer=?'r &Geihd'xso_hq, pollTimeoutMs=?'r &Geihd'xso_hq, offsetCommitPeriodMs=1, maxRetries=0, maxUncommittedOffsets=0, firstPollOffsetStrategy=null, kafkaSpoutStreams=null, tuplesBuilder=null, retryService=, firstPollOffsetStrategy=, topics=?'r &Geihd'xso_hq, topicWildcardPattern=}", string0); // (Primitive) Original Value: KafkaSpoutConfig{kafkaProps=null, keyDeserializer=null, valueDeserializer=?'r &Geihd'xso_hq, pollTimeoutMs=?'r &Geihd'xso_hq, offsetCommitPeriodMs=1, maxRetries=0, maxUncommittedOffsets=0, firstPollOffsetStrategy=null, kafkaSpoutStreams=null, tuplesBuilder=null, retryService=, firstPollOffsetStrategy=, topics=?'r &Geihd'xso_hq, topicWildcardPattern=} | Regression Value: KafkaSpoutConfig{kafkaProps=null, keyDeserializer=null, valueDeserializer=?'r &Geihd'xso_hq, pollTimeoutMs=?'r &Geihd'xso_hq, offsetCommitPeriodMs=1, maxUncommittedOffsets=0, firstPollOffsetStrategy=null, kafkaSpoutStreams=null, tuplesBuilder=null, retryService=, firstPollOffsetStrategy=, topics=?'r &Geihd'xso_hq, topicWildcardPattern=}
  }
}
