/*
 * This file was automatically generated by EvoSuite
 * Wed Jul 03 17:20:43 GMT 2019
 */

package br.com;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.Ball;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Ball_ESTest extends Ball_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Ball ball0 = new Ball((-1017L), 1796, 0, "9XOHngpGZC\"_", ", maxRetries=", "9XOHngpGZC\"_", "", "_p:D2}!FfQ$c'B", "", ", maxRetries=", "", ", maxRetries=");
      assertEquals("KafkaSpoutConfig{kafkaProps=_p:D2}!FfQ$c'B, keyDeserializer=, valueDeserializer=, maxRetries=, pollTimeoutMs=, maxRetries=, offsetCommitPeriodMs=-1017, maxUncommittedOffsets=0, firstPollOffsetStrategy=9XOHngpGZC\"_, kafkaSpoutStreams=, maxRetries=, tuplesBuilder=9XOHngpGZC\"_, retryService=, topics=, topicWildcardPattern=, maxRetries=}", ball0.getFinalString()); // (Inspector) Original Value: KafkaSpoutConfig{kafkaProps=_p:D2}!FfQ$c'B, keyDeserializer=, valueDeserializer=, maxRetries=, pollTimeoutMs=, maxRetries=, offsetCommitPeriodMs=-1017, maxUncommittedOffsets=0, firstPollOffsetStrategy=9XOHngpGZC"_, kafkaSpoutStreams=, maxRetries=, tuplesBuilder=9XOHngpGZC"_, retryService=, topics=, topicWildcardPattern=, maxRetries=} | Regression Value: KafkaSpoutConfig{kafkaProps=_p:D2}!FfQ$c'B, keyDeserializer=, valueDeserializer=, maxRetries=, pollTimeoutMs=, maxRetries=, offsetCommitPeriodMs=-1017, maxRetries=1796, maxUncommittedOffsets=0, firstPollOffsetStrategy=9XOHngpGZC"_, kafkaSpoutStreams=, maxRetries=, tuplesBuilder=9XOHngpGZC"_, retryService=, topics=, topicWildcardPattern=, maxRetries=}
  }
}
