/*
 * This file was automatically generated by EvoSuite
 * Wed Jul 03 17:56:19 GMT 2019
 */

package br.com;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.Ball;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Ball_ESTest extends Ball_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Ball ball0 = new Ball((-5240L), 0, 0, "]e,/,X!D9IaZZ==YF", "", "br.com.Ball", "", "", "", "br.com.Ball", "ukv]hw*H!R?ltByc8dF", ", offsetCommitPeriodMs=");
      String string0 = ball0.finalString();
      assertEquals("KafkaSpoutConfig{kafkaProps=, keyDeserializer=, valueDeserializer=br.com.Ball, pollTimeoutMs=br.com.Ball, offsetCommitPeriodMs=-5240, maxUncommittedOffsets=0, firstPollOffsetStrategy=]e,/,X!D9IaZZ==YF, kafkaSpoutStreams=, tuplesBuilder=br.com.Ball, retryService=, topics=ukv]hw*H!R?ltByc8dF, topicWildcardPattern=, offsetCommitPeriodMs=}", string0); // (Primitive) Original Value: KafkaSpoutConfig{kafkaProps=, keyDeserializer=, valueDeserializer=br.com.Ball, pollTimeoutMs=br.com.Ball, offsetCommitPeriodMs=-5240, maxUncommittedOffsets=0, firstPollOffsetStrategy=]e,/,X!D9IaZZ==YF, kafkaSpoutStreams=, tuplesBuilder=br.com.Ball, retryService=, topics=ukv]hw*H!R?ltByc8dF, topicWildcardPattern=, offsetCommitPeriodMs=} | Regression Value: KafkaSpoutConfig{kafkaProps=, keyDeserializer=, valueDeserializer=br.com.Ball, pollTimeoutMs=br.com.Ball, offsetCommitPeriodMs=-5240, maxRetries=0, maxUncommittedOffsets=0, firstPollOffsetStrategy=]e,/,X!D9IaZZ==YF, kafkaSpoutStreams=, tuplesBuilder=br.com.Ball, retryService=, topics=ukv]hw*H!R?ltByc8dF, topicWildcardPattern=, offsetCommitPeriodMs=}
  }
}
