/*
 * This file was automatically generated by EvoSuite
 * Wed Jul 03 18:38:30 GMT 2019
 */

package br.com;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.Ball;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Ball_ESTest extends Ball_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Ball ball0 = new Ball(1566L, (-1), (-2171), "", "", (String) null, "3Pyv/C-kep&z<WRNP h", "", "PJ_0N;w", "$", (String) null, "3Pyv/C-kep&z<WRNP h");
      String string0 = ball0.finalString();
      assertEquals("KafkaSpoutConfig{kafkaProps=, keyDeserializer=PJ_0N;w, valueDeserializer=$, pollTimeoutMs=$, offsetCommitPeriodMs=1566, maxUncommittedOffsets=-2171, firstPollOffsetStrategy=, kafkaSpoutStreams=, tuplesBuilder=null, retryService=3Pyv/C-kep&z<WRNP h, topics=null, topicWildcardPattern=3Pyv/C-kep&z<WRNP h}", string0); // (Primitive) Original Value: KafkaSpoutConfig{kafkaProps=, keyDeserializer=PJ_0N;w, valueDeserializer=$, pollTimeoutMs=$, offsetCommitPeriodMs=1566, maxUncommittedOffsets=-2171, firstPollOffsetStrategy=, kafkaSpoutStreams=, tuplesBuilder=null, retryService=3Pyv/C-kep&z<WRNP h, topics=null, topicWildcardPattern=3Pyv/C-kep&z<WRNP h} | Regression Value: KafkaSpoutConfig{kafkaProps=, keyDeserializer=PJ_0N;w, valueDeserializer=$, pollTimeoutMs=$, offsetCommitPeriodMs=1566, maxRetries=-1, maxUncommittedOffsets=-2171, firstPollOffsetStrategy=, kafkaSpoutStreams=, tuplesBuilder=null, retryService=3Pyv/C-kep&z<WRNP h, topics=null, topicWildcardPattern=3Pyv/C-kep&z<WRNP h}
  }
}
