/*
 * This file was automatically generated by EvoSuite
 * Wed Jul 03 18:18:13 GMT 2019
 */

package br.com;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.Ball;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Ball_ESTest extends Ball_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Ball ball0 = new Ball(65L, (-1797), (-1797), "1r\"y_0I[", "1r\"y_0I[", "1r\"y_0I[", "", "", "", "~4Y7T/UH", "", "~4Y7T/UH");
      String string0 = ball0.finalString();
      assertEquals("KafkaSpoutConfig{kafkaProps=, keyDeserializer=, valueDeserializer=~4Y7T/UH, pollTimeoutMs=~4Y7T/UH, offsetCommitPeriodMs=65, maxUncommittedOffsets=-1797, firstPollOffsetStrategy=1r\"y_0I[, kafkaSpoutStreams=1r\"y_0I[, tuplesBuilder=1r\"y_0I[, retryService=, topics=, topicWildcardPattern=~4Y7T/UH}", string0); // (Primitive) Original Value: KafkaSpoutConfig{kafkaProps=, keyDeserializer=, valueDeserializer=~4Y7T/UH, pollTimeoutMs=~4Y7T/UH, offsetCommitPeriodMs=65, maxUncommittedOffsets=-1797, firstPollOffsetStrategy=1r"y_0I[, kafkaSpoutStreams=1r"y_0I[, tuplesBuilder=1r"y_0I[, retryService=, topics=, topicWildcardPattern=~4Y7T/UH} | Regression Value: KafkaSpoutConfig{kafkaProps=, keyDeserializer=, valueDeserializer=~4Y7T/UH, pollTimeoutMs=~4Y7T/UH, offsetCommitPeriodMs=65, maxRetries=-1797, maxUncommittedOffsets=-1797, firstPollOffsetStrategy=1r"y_0I[, kafkaSpoutStreams=1r"y_0I[, tuplesBuilder=1r"y_0I[, retryService=, topics=, topicWildcardPattern=~4Y7T/UH}
  }
}
