/*
 * This file was automatically generated by EvoSuite
 * Wed May 22 16:26:08 GMT 2019
 */

package br.com;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.Ball;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Ball_ESTest extends Ball_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Ball ball0 = new Ball(4116L, 2213, 2213, ", maxUncommittedOffsets=", ", maxUncommittedOffsets=", ", maxUncommittedOffsets=", ", maxUncommittedOffsets=", ", kafkaSpoutStreams=", "O!B'tNx<ygz7zZk", ", kafkaSpoutStreams=", "O!B'tNx<ygz7zZk", ", maxUncommittedOffsets=");
      String string0 = ball0.finalString();
      assertEquals("KafkaSpoutConfig{kafkaProps=, kafkaSpoutStreams=, keyDeserializer=O!B'tNx<ygz7zZk, valueDeserializer=, kafkaSpoutStreams=, pollTimeoutMs=, kafkaSpoutStreams=, offsetCommitPeriodMs=4116, maxRetries=2213, maxUncommittedOffsets=2213, firstPollOffsetStrategy=, maxUncommittedOffsets=, kafkaSpoutStreams=, maxUncommittedOffsets=, tuplesBuilder=, maxUncommittedOffsets=, retryService=, maxUncommittedOffsets=, topics=O!B'tNx<ygz7zZk, topicWildcardPattern=, maxUncommittedOffsets=}", string0); // (Primitive) Original Value: KafkaSpoutConfig{kafkaProps=, kafkaSpoutStreams=, keyDeserializer=O!B'tNx<ygz7zZk, valueDeserializer=, kafkaSpoutStreams=, pollTimeoutMs=, kafkaSpoutStreams=, offsetCommitPeriodMs=4116, maxRetries=2213, maxUncommittedOffsets=2213, firstPollOffsetStrategy=, maxUncommittedOffsets=, kafkaSpoutStreams=, maxUncommittedOffsets=, tuplesBuilder=, maxUncommittedOffsets=, retryService=, maxUncommittedOffsets=, topics=O!B'tNx<ygz7zZk, topicWildcardPattern=, maxUncommittedOffsets=} | Regression Value: KafkaSpoutConfig{kafkaProps=, kafkaSpoutStreams=, keyDeserializer=O!B'tNx<ygz7zZk, valueDeserializer=, kafkaSpoutStreams=, pollTimeoutMs=, kafkaSpoutStreams=, offsetCommitPeriodMs=4116, maxUncommittedOffsets=2213, firstPollOffsetStrategy=, maxUncommittedOffsets=, kafkaSpoutStreams=, maxUncommittedOffsets=, tuplesBuilder=, maxUncommittedOffsets=, retryService=, maxUncommittedOffsets=, topics=O!B'tNx<ygz7zZk, topicWildcardPattern=, maxUncommittedOffsets=}
  }
}
