/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 05 16:54:41 GMT 2019
 */

package br.com;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.Ball;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Ball_ESTest extends Ball_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Ball ball0 = new Ball(0L, 0, 0, "=S.Sc1lfpB", "", "=S.Sc1lfpB", "=S.Sc1lfpB", "=S.Sc1lfpB", "=S.Sc1lfpB", "=S.Sc1lfpB", "", "$0Tc1S&|");
      String string0 = ball0.finalString();
      assertEquals("KafkaSpoutConfig{kafkaProps==S.Sc1lfpB, keyDeserializer==S.Sc1lfpB, valueDeserializer==S.Sc1lfpB, pollTimeoutMs==S.Sc1lfpB, offsetCommitPeriodMs=0, maxUncommittedOffsets=0, firstPollOffsetStrategy==S.Sc1lfpB, kafkaSpoutStreams=, tuplesBuilder==S.Sc1lfpB, retryService==S.Sc1lfpB, topics=, topicWildcardPattern=$0Tc1S&|}", string0); // (Primitive) Original Value: KafkaSpoutConfig{kafkaProps==S.Sc1lfpB, keyDeserializer==S.Sc1lfpB, valueDeserializer==S.Sc1lfpB, pollTimeoutMs==S.Sc1lfpB, offsetCommitPeriodMs=0, maxUncommittedOffsets=0, firstPollOffsetStrategy==S.Sc1lfpB, kafkaSpoutStreams=, tuplesBuilder==S.Sc1lfpB, retryService==S.Sc1lfpB, topics=, topicWildcardPattern=$0Tc1S&|} | Regression Value: KafkaSpoutConfig{kafkaProps==S.Sc1lfpB, keyDeserializer==S.Sc1lfpB, valueDeserializer==S.Sc1lfpB, pollTimeoutMs==S.Sc1lfpB, offsetCommitPeriodMs=0, maxRetries=0, maxUncommittedOffsets=0, firstPollOffsetStrategy==S.Sc1lfpB, kafkaSpoutStreams=, tuplesBuilder==S.Sc1lfpB, retryService==S.Sc1lfpB, topics=, topicWildcardPattern=$0Tc1S&|}
  }
}
