/*
 * This file was automatically generated by EvoSuite
 * Mon May 13 12:56:28 GMT 2019
 */

package br.com;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.Ball;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Ball_ESTest extends Ball_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Ball ball0 = new Ball(833L, 0, 2231, "", ":z^DuNPJ9", ", valueDeserializer=", ":z^DuNPJ9", ", valueDeserializer=", "[Ij4I]&][E", "[Ij4I]&][E", "", "");
      String string0 = ball0.getFinalString();
      assertEquals("KafkaSpoutConfig{kafkaProps=, valueDeserializer=, keyDeserializer=[Ij4I]&][E, valueDeserializer=[Ij4I]&][E, pollTimeoutMs=[Ij4I]&][E, offsetCommitPeriodMs=833, maxRetries=0, maxUncommittedOffsets=2231, firstPollOffsetStrategy=, kafkaSpoutStreams=:z^DuNPJ9, tuplesBuilder=, valueDeserializer=, retryService=:z^DuNPJ9, topics=, topicWildcardPattern=}", string0); // (Primitive) Original Value: KafkaSpoutConfig{kafkaProps=, valueDeserializer=, keyDeserializer=[Ij4I]&][E, valueDeserializer=[Ij4I]&][E, pollTimeoutMs=[Ij4I]&][E, offsetCommitPeriodMs=833, maxRetries=0, maxUncommittedOffsets=2231, firstPollOffsetStrategy=, kafkaSpoutStreams=:z^DuNPJ9, tuplesBuilder=, valueDeserializer=, retryService=:z^DuNPJ9, topics=, topicWildcardPattern=} | Regression Value: KafkaSpoutConfig{kafkaProps=, valueDeserializer=, keyDeserializer=[Ij4I]&][E, valueDeserializer=[Ij4I]&][E, pollTimeoutMs=[Ij4I]&][E, offsetCommitPeriodMs=833, maxUncommittedOffsets=2231, firstPollOffsetStrategy=, kafkaSpoutStreams=:z^DuNPJ9, tuplesBuilder=, valueDeserializer=, retryService=:z^DuNPJ9, topics=, topicWildcardPattern=}
  }
}
