/*
 * This file was automatically generated by EvoSuite
 * Wed Jul 03 17:16:45 GMT 2019
 */

package br.com;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.Ball;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Ball_ESTest extends Ball_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Ball ball0 = new Ball((-1L), 1347, 0, "uPCdExXP\"#P", "uPCdExXP\"#P", "", "uPCdExXP\"#P", "", "", "", (String) null, (String) null);
      String string0 = ball0.finalString();
      assertEquals("KafkaSpoutConfig{kafkaProps=, keyDeserializer=, valueDeserializer=, pollTimeoutMs=, offsetCommitPeriodMs=-1, maxUncommittedOffsets=0, firstPollOffsetStrategy=uPCdExXP\"#P, kafkaSpoutStreams=uPCdExXP\"#P, tuplesBuilder=, retryService=uPCdExXP\"#P, topics=null, topicWildcardPattern=null}", string0); // (Primitive) Original Value: KafkaSpoutConfig{kafkaProps=, keyDeserializer=, valueDeserializer=, pollTimeoutMs=, offsetCommitPeriodMs=-1, maxUncommittedOffsets=0, firstPollOffsetStrategy=uPCdExXP"#P, kafkaSpoutStreams=uPCdExXP"#P, tuplesBuilder=, retryService=uPCdExXP"#P, topics=null, topicWildcardPattern=null} | Regression Value: KafkaSpoutConfig{kafkaProps=, keyDeserializer=, valueDeserializer=, pollTimeoutMs=, offsetCommitPeriodMs=-1, maxRetries=1347, maxUncommittedOffsets=0, firstPollOffsetStrategy=uPCdExXP"#P, kafkaSpoutStreams=uPCdExXP"#P, tuplesBuilder=, retryService=uPCdExXP"#P, topics=null, topicWildcardPattern=null}
  }
}
