/*
 * This file was automatically generated by EvoSuite
 * Wed Jul 03 18:21:11 GMT 2019
 */

package br.com;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.Ball;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Ball_ESTest extends Ball_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Ball ball0 = new Ball(0L, (-2631), 0, (String) null, (String) null, (String) null, "", "d*i5|sHI.`J", "WpKv]L<9Z>;8fw", "4^15y", "d*i5|sHI.`J", "4^15y");
      String string0 = ball0.finalString();
      assertEquals("KafkaSpoutConfig{kafkaProps=d*i5|sHI.`J, keyDeserializer=WpKv]L<9Z>;8fw, valueDeserializer=4^15y, pollTimeoutMs=4^15y, offsetCommitPeriodMs=0, maxUncommittedOffsets=0, firstPollOffsetStrategy=null, kafkaSpoutStreams=null, tuplesBuilder=null, retryService=, topics=d*i5|sHI.`J, topicWildcardPattern=4^15y}", string0); // (Primitive) Original Value: KafkaSpoutConfig{kafkaProps=d*i5|sHI.`J, keyDeserializer=WpKv]L<9Z>;8fw, valueDeserializer=4^15y, pollTimeoutMs=4^15y, offsetCommitPeriodMs=0, maxUncommittedOffsets=0, firstPollOffsetStrategy=null, kafkaSpoutStreams=null, tuplesBuilder=null, retryService=, topics=d*i5|sHI.`J, topicWildcardPattern=4^15y} | Regression Value: KafkaSpoutConfig{kafkaProps=d*i5|sHI.`J, keyDeserializer=WpKv]L<9Z>;8fw, valueDeserializer=4^15y, pollTimeoutMs=4^15y, offsetCommitPeriodMs=0, maxRetries=-2631, maxUncommittedOffsets=0, firstPollOffsetStrategy=null, kafkaSpoutStreams=null, tuplesBuilder=null, retryService=, topics=d*i5|sHI.`J, topicWildcardPattern=4^15y}
  }
}
