/*
 * This file was automatically generated by EvoSuite
 * Wed Jul 03 18:01:29 GMT 2019
 */

package br.com;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.Ball;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Ball_ESTest extends Ball_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Ball ball0 = new Ball(0L, 0, 0, "AGWRuoVy~H.gvmTs", "AGWRuoVy~H.gvmTs", "", "AGWRuoVy~H.gvmTs", "AGWRuoVy~H.gvmTs", ", maxRetries=", (String) null, "", "L4JEv");
      String string0 = ball0.finalString();
      assertEquals("KafkaSpoutConfig{kafkaProps=AGWRuoVy~H.gvmTs, keyDeserializer=, maxRetries=, valueDeserializer=null, pollTimeoutMs=null, offsetCommitPeriodMs=0, maxUncommittedOffsets=0, firstPollOffsetStrategy=AGWRuoVy~H.gvmTs, kafkaSpoutStreams=AGWRuoVy~H.gvmTs, tuplesBuilder=, retryService=AGWRuoVy~H.gvmTs, topics=, topicWildcardPattern=L4JEv}", string0); // (Primitive) Original Value: KafkaSpoutConfig{kafkaProps=AGWRuoVy~H.gvmTs, keyDeserializer=, maxRetries=, valueDeserializer=null, pollTimeoutMs=null, offsetCommitPeriodMs=0, maxUncommittedOffsets=0, firstPollOffsetStrategy=AGWRuoVy~H.gvmTs, kafkaSpoutStreams=AGWRuoVy~H.gvmTs, tuplesBuilder=, retryService=AGWRuoVy~H.gvmTs, topics=, topicWildcardPattern=L4JEv} | Regression Value: KafkaSpoutConfig{kafkaProps=AGWRuoVy~H.gvmTs, keyDeserializer=, maxRetries=, valueDeserializer=null, pollTimeoutMs=null, offsetCommitPeriodMs=0, maxRetries=0, maxUncommittedOffsets=0, firstPollOffsetStrategy=AGWRuoVy~H.gvmTs, kafkaSpoutStreams=AGWRuoVy~H.gvmTs, tuplesBuilder=, retryService=AGWRuoVy~H.gvmTs, topics=, topicWildcardPattern=L4JEv}
  }
}
