/*
 * This file was automatically generated by EvoSuite
 * Wed Jul 03 18:10:34 GMT 2019
 */

package br.com;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.Ball;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Ball_ESTest extends Ball_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Ball ball0 = new Ball(0L, 0, 0, "", "", (String) null, (String) null, (String) null, "?uxfJA", "", "", "");
      String string0 = ball0.finalString();
      assertEquals("KafkaSpoutConfig{kafkaProps=null, keyDeserializer=?uxfJA, valueDeserializer=, pollTimeoutMs=, offsetCommitPeriodMs=0, maxUncommittedOffsets=0, firstPollOffsetStrategy=, kafkaSpoutStreams=, tuplesBuilder=null, retryService=null, topics=, topicWildcardPattern=}", string0); // (Primitive) Original Value: KafkaSpoutConfig{kafkaProps=null, keyDeserializer=?uxfJA, valueDeserializer=, pollTimeoutMs=, offsetCommitPeriodMs=0, maxUncommittedOffsets=0, firstPollOffsetStrategy=, kafkaSpoutStreams=, tuplesBuilder=null, retryService=null, topics=, topicWildcardPattern=} | Regression Value: KafkaSpoutConfig{kafkaProps=null, keyDeserializer=?uxfJA, valueDeserializer=, pollTimeoutMs=, offsetCommitPeriodMs=0, maxRetries=0, maxUncommittedOffsets=0, firstPollOffsetStrategy=, kafkaSpoutStreams=, tuplesBuilder=null, retryService=null, topics=, topicWildcardPattern=}
  }
}
