/*
 * This file was automatically generated by EvoSuite
 * Wed Jul 03 17:54:10 GMT 2019
 */

package br.com;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.Ball;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Ball_ESTest extends Ball_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Ball ball0 = new Ball((-1L), (-1099), 1, "/qMGA/IF", "/qMGA/IF", "/qMGA/IF", "/qMGA/IF", "hm'!;rP1N#=J^f", "/qMGA/IF", "hm'!;rP1N#=J^f", "hm'!;rP1N#=J^f", "hm'!;rP1N#=J^f");
      String string0 = ball0.finalString();
      assertEquals("KafkaSpoutConfig{kafkaProps=hm'!;rP1N#=J^f, keyDeserializer=/qMGA/IF, valueDeserializer=hm'!;rP1N#=J^f, pollTimeoutMs=hm'!;rP1N#=J^f, offsetCommitPeriodMs=-1, maxUncommittedOffsets=1, firstPollOffsetStrategy=/qMGA/IF, kafkaSpoutStreams=/qMGA/IF, tuplesBuilder=/qMGA/IF, retryService=/qMGA/IF, topics=hm'!;rP1N#=J^f, topicWildcardPattern=hm'!;rP1N#=J^f}", string0); // (Primitive) Original Value: KafkaSpoutConfig{kafkaProps=hm'!;rP1N#=J^f, keyDeserializer=/qMGA/IF, valueDeserializer=hm'!;rP1N#=J^f, pollTimeoutMs=hm'!;rP1N#=J^f, offsetCommitPeriodMs=-1, maxUncommittedOffsets=1, firstPollOffsetStrategy=/qMGA/IF, kafkaSpoutStreams=/qMGA/IF, tuplesBuilder=/qMGA/IF, retryService=/qMGA/IF, topics=hm'!;rP1N#=J^f, topicWildcardPattern=hm'!;rP1N#=J^f} | Regression Value: KafkaSpoutConfig{kafkaProps=hm'!;rP1N#=J^f, keyDeserializer=/qMGA/IF, valueDeserializer=hm'!;rP1N#=J^f, pollTimeoutMs=hm'!;rP1N#=J^f, offsetCommitPeriodMs=-1, maxRetries=-1099, maxUncommittedOffsets=1, firstPollOffsetStrategy=/qMGA/IF, kafkaSpoutStreams=/qMGA/IF, tuplesBuilder=/qMGA/IF, retryService=/qMGA/IF, topics=hm'!;rP1N#=J^f, topicWildcardPattern=hm'!;rP1N#=J^f}
  }
}
