/*
 * This file was automatically generated by EvoSuite
 * Wed Jul 03 17:55:35 GMT 2019
 */

package br.com;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.Ball;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Ball_ESTest extends Ball_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Ball ball0 = new Ball(0L, 2716, (-1), ", pollTimeoutMs=", ", keyDeserializer=", ", pollTimeoutMs=", "cfOZ[b8_f0qGnxbs", "UqxDM7HKw&", ", pollTimeoutMs=", "", ", kafkaSpoutStreams=", "j7OXq*]e<Cl=/{t#");
      String string0 = ball0.finalString();
      assertEquals("KafkaSpoutConfig{kafkaProps=UqxDM7HKw&, keyDeserializer=, pollTimeoutMs=, valueDeserializer=, pollTimeoutMs=, offsetCommitPeriodMs=0, maxUncommittedOffsets=-1, firstPollOffsetStrategy=, pollTimeoutMs=, kafkaSpoutStreams=, keyDeserializer=, tuplesBuilder=, pollTimeoutMs=, retryService=cfOZ[b8_f0qGnxbs, topics=, kafkaSpoutStreams=, topicWildcardPattern=j7OXq*]e<Cl=/{t#}", string0); // (Primitive) Original Value: KafkaSpoutConfig{kafkaProps=UqxDM7HKw&, keyDeserializer=, pollTimeoutMs=, valueDeserializer=, pollTimeoutMs=, offsetCommitPeriodMs=0, maxUncommittedOffsets=-1, firstPollOffsetStrategy=, pollTimeoutMs=, kafkaSpoutStreams=, keyDeserializer=, tuplesBuilder=, pollTimeoutMs=, retryService=cfOZ[b8_f0qGnxbs, topics=, kafkaSpoutStreams=, topicWildcardPattern=j7OXq*]e<Cl=/{t#} | Regression Value: KafkaSpoutConfig{kafkaProps=UqxDM7HKw&, keyDeserializer=, pollTimeoutMs=, valueDeserializer=, pollTimeoutMs=, offsetCommitPeriodMs=0, maxRetries=2716, maxUncommittedOffsets=-1, firstPollOffsetStrategy=, pollTimeoutMs=, kafkaSpoutStreams=, keyDeserializer=, tuplesBuilder=, pollTimeoutMs=, retryService=cfOZ[b8_f0qGnxbs, topics=, kafkaSpoutStreams=, topicWildcardPattern=j7OXq*]e<Cl=/{t#}
  }
}
