/*
 * This file was automatically generated by EvoSuite
 * Wed Jul 03 17:33:55 GMT 2019
 */

package br.com;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.Ball;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Ball_ESTest extends Ball_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Ball ball0 = new Ball((-409L), 1252, 1252, "Uj H)B=7h9S5AIf0", ", offsetCommitPeriodMs=", ", offsetCommitPeriodMs=", (String) null, "Uj H)B=7h9S5AIf0", ">2)", ", offsetCommitPeriodMs=", "Uj H)B=7h9S5AIf0", "$U;");
      String string0 = ball0.finalString();
      assertEquals("KafkaSpoutConfig{kafkaProps=Uj H)B=7h9S5AIf0, keyDeserializer=>2), valueDeserializer=, offsetCommitPeriodMs=, pollTimeoutMs=, offsetCommitPeriodMs=, offsetCommitPeriodMs=-409, maxUncommittedOffsets=1252, firstPollOffsetStrategy=Uj H)B=7h9S5AIf0, kafkaSpoutStreams=, offsetCommitPeriodMs=, tuplesBuilder=, offsetCommitPeriodMs=, retryService=null, topics=Uj H)B=7h9S5AIf0, topicWildcardPattern=$U;}", string0); // (Primitive) Original Value: KafkaSpoutConfig{kafkaProps=Uj H)B=7h9S5AIf0, keyDeserializer=>2), valueDeserializer=, offsetCommitPeriodMs=, pollTimeoutMs=, offsetCommitPeriodMs=, offsetCommitPeriodMs=-409, maxUncommittedOffsets=1252, firstPollOffsetStrategy=Uj H)B=7h9S5AIf0, kafkaSpoutStreams=, offsetCommitPeriodMs=, tuplesBuilder=, offsetCommitPeriodMs=, retryService=null, topics=Uj H)B=7h9S5AIf0, topicWildcardPattern=$U;} | Regression Value: KafkaSpoutConfig{kafkaProps=Uj H)B=7h9S5AIf0, keyDeserializer=>2), valueDeserializer=, offsetCommitPeriodMs=, pollTimeoutMs=, offsetCommitPeriodMs=, offsetCommitPeriodMs=-409, maxRetries=1252, maxUncommittedOffsets=1252, firstPollOffsetStrategy=Uj H)B=7h9S5AIf0, kafkaSpoutStreams=, offsetCommitPeriodMs=, tuplesBuilder=, offsetCommitPeriodMs=, retryService=null, topics=Uj H)B=7h9S5AIf0, topicWildcardPattern=$U;}
  }
}
